// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4ELRR_oZghWWkYUNWPfrmU0-pPMvDr4',
    appId: '1:995928367407:web:2a7e47617574e775c0c1da',
    messagingSenderId: '995928367407',
    projectId: 'faisal-movers-1d63e',
    authDomain: 'faisal-movers-1d63e.firebaseapp.com',
    databaseURL: 'https://faisal-movers-1d63e-default-rtdb.firebaseio.com',
    storageBucket: 'faisal-movers-1d63e.appspot.com',
    measurementId: 'G-SLCWWBDBTF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZF8qv1NrZGs4xJUcQuBE6DdJczPFddY',
    appId: '1:995928367407:ios:0d21363f15e8381cc0c1da',
    messagingSenderId: '995928367407',
    projectId: 'faisal-movers-1d63e',
    databaseURL: 'https://faisal-movers-1d63e-default-rtdb.firebaseio.com',
    storageBucket: 'faisal-movers-1d63e.appspot.com',
    iosBundleId: 'com.example.faisalMovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZF8qv1NrZGs4xJUcQuBE6DdJczPFddY',
    appId: '1:995928367407:ios:0d21363f15e8381cc0c1da',
    messagingSenderId: '995928367407',
    projectId: 'faisal-movers-1d63e',
    databaseURL: 'https://faisal-movers-1d63e-default-rtdb.firebaseio.com',
    storageBucket: 'faisal-movers-1d63e.appspot.com',
    iosBundleId: 'com.example.faisalMovers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb4ELRR_oZghWWkYUNWPfrmU0-pPMvDr4',
    appId: '1:995928367407:web:a579c3d279e133c5c0c1da',
    messagingSenderId: '995928367407',
    projectId: 'faisal-movers-1d63e',
    authDomain: 'faisal-movers-1d63e.firebaseapp.com',
    databaseURL: 'https://faisal-movers-1d63e-default-rtdb.firebaseio.com',
    storageBucket: 'faisal-movers-1d63e.appspot.com',
    measurementId: 'G-7PMYS9749N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzWTLd0Jj_jAylMEOHeSY8NblBUhUcD4',
    appId: '1:995928367407:android:43c99dc2cdd90360c0c1da',
    messagingSenderId: '995928367407',
    projectId: 'faisal-movers-1d63e',
    databaseURL: 'https://faisal-movers-1d63e-default-rtdb.firebaseio.com',
    storageBucket: 'faisal-movers-1d63e.appspot.com',
  );

}